nixpkgs: Update submodule:
* include fixes for GHC segfaulting: (NixOS/nixpkgs#129247, NixOS/nixpkgs#129289)
* musl 1.2.2, including this important fix from musl 1.2.0:
  https://github.com/nh2/static-haskell-nix/pull/98#issuecomment-664676038
* workaround for fontforge execution failure due to wrong RPATH:
  https://github.com/NixOS/nixpkgs/pull/94126
* ilmbase musl compilation error:
  https://github.com/NixOS/nixpkgs/pull/94205
* mesa: Fix `-Werror=int-conversion` build error on musl:
  https://github.com/NixOS/nixpkgs/pull/94207

survey:

* Update file in which stackage packages are listed.
  See nixpkgs commit

      7f236bd4 - hackage2nix: Split configuration, auto disable hydra builds