survey: Use isProperHaskellPackage on final overlay.
This fixes the problem that until now you couldn't properly override the
Haskell package set returned by survey, like this:

    static_haskellPackages = static-stack2nix-builder.haskell-static-nix_output.haskellPackages;

    # Override some packages in the snapshot.
    static_haskellPackages_with_fixes = static_haskellPackages.override (old: {
      overrides = pkgs.lib.composeExtensions (old.overrides or (_: _: {})) (self: super: {

        # Remove nixpkgs-specific patch that no longer applies to >= 0.16
        servant-client-core = pkgs.haskell.lib.overrideCabal super.servant-client-core (old: {
          patches = with pkgs.lib;
            filter (p: !(hasSuffix "streamBody.patch" p)) (old.patches or []);
        });

      });
    });

Until now, using `.override` in `static_haskellPackages.override` resulted in
`value is a function while a set was expected`:

    error: while evaluating the attribute 'override' at undefined position:
    while evaluating anonymous function at survey/default.nix:1012:35, called from undefined position:
    while evaluating 'isExecutable' at survey/default.nix:101:18, called from survey/default.nix:1013:43:
    while evaluating 'overrideCabal' at pkgs/development/haskell-modules/lib.nix:37:24, called from survey/default.nix:102:6:
    value is a function while a set was expected, at pkgs/development/haskell-modules/lib.nix:37:28

because it tried to access run `.isExecutable` on the `.override` key of a
`haskellPackages` Haskell package set.